### PR TITLE
[fix] map:remove sequence of keys

### LINKED ISSUE #1656: Align map:remove with 3.1 F&O spec to accept zero-or-more keys
### What is the problem

eXist's implementation of `map:remove` allows only a single key:

> `map:remove($map as map, $key as xs:string)`

### What did you expect

The XQuery 3.1 F&O spec says that `map:remove` can take 0 or more keys:

> `map:remove($map as map(*), $keys as xs:anyAtomicType*)`

See https://www.w3.org/TR/xpath-functions-31/#func-map-remove.

Besides the cardinality difference, note that keys can be of `xs:anyAtomicType`, not just `xs:string`.

### Describe how to reproduce or add a test

This example is taken from the spec at the link above:

```xquery
xquery version "3.1";

let $week := map{0:"Sonntag", 1:"Montag", 2:"Dienstag",
       3:"Mittwoch", 4:"Donnerstag", 5:"Freitag", 6:"Samstag"}
return
    map:remove($week, (0, 6 to 7)) 
```

BaseX and Saxon return the expected result: 

```xquery
map{1:"Montag",2:"Dienstag",3:"Mittwoch",4:"Donnerstag",5:"Freitag"}
```

eXist returns the following error:

> err:XPTY0004 checking function parameter 2 in call map:remove($week, untyped-value-check[xs:string, ( 0, 6 to 7 )]): XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: map:remove($map as map, $key as xs:string) map. Expected cardinality: exactly one, got 3. 

### Context information

- eXist-db version + Git Revision hash: eXist 3.7.0-SNAPSHOT+9091c3032
- Java version: Oracle JDK 1.8.0_152
- Operating system: macOS 10.13.1
- 32 or 64 bit: 64 bit
- Any custom changes in e.g. conf.xml: none

### PR DESCRIPTION
**Pull request by line-o**
### Description:

AbstractMapType.remove and all overrides now expect an array of
AtomicValues.

MapFunction.remove was adapted to take that into account.

### Reference:

fixes #1656 

### Type of tests:

Add tests to XQsuite to ensure sequences of keys can be deleted and
the changes do not break behaviour for non existing keys.

### CODE REVIEW

File: exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java [hunk 1]
```diff
@@ -145,9 +145,13 @@ public Sequence eval(final Sequence[] args, final Sequence contextSequence) thro
         return null;
     }
 
-    private Sequence remove(final Sequence[] args) {
+    private Sequence remove(final Sequence[] args) throws XPathException {
         final AbstractMapType map = (AbstractMapType) args[0].itemAt(0);
-        return map.remove((AtomicValue) args[1].itemAt(0));
+        AtomicValue[] keys = new AtomicValue[args[1].getItemCount()];
```
Comment (dizzzz) [inline exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java]: Could be replaced with nice lambda/collector expression?

Comment (line-o) [reply exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java]: @dizzzz Do you have a link to an example?

Comment (line-o) [reply exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java]: I had a quick look around and I cannot see how this could be applied here.

File: exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java [hunk 2]
```diff
@@ -59,12 +60,16 @@ public int size() {
     }
 
     @Override
-    public AbstractMapType remove(AtomicValue key) {
-        try {
+    public AbstractMapType remove(AtomicValue[] keysAtomicValues) throws XPathException {
+        for (final AtomicValue key: keysAtomicValues) {
```
Comment (dizzzz) [inline exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java]: I do not understand the logic here :-)

Comment (line-o) [reply exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java]: For some reason Maps with just one key have their own java representation.
`let $a := map { 'a': 1 }` 
this implementation ensures that `map:remove($a, ('z','zz','zzz'))`, `map:remove($a, ('z','a'))` and `map:remove($a, 'a')` behave as expected.

File: exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java [hunk 3]
```diff
@@ -145,9 +145,16 @@ public Sequence eval(final Sequence[] args, final Sequence contextSequence) thro
         return null;
     }
 
-    private Sequence remove(final Sequence[] args) {
+    private Sequence remove(final Sequence[] args) throws XPathException {
         final AbstractMapType map = (AbstractMapType) args[0].itemAt(0);
-        return map.remove((AtomicValue) args[1].itemAt(0));
+
+        final int length = args[1].getItemCount();
+        AtomicValue[] keys = new AtomicValue[length];
```
Comment (adamretter) [inline exist-core/src/main/java/org/exist/xquery/functions/map/MapFunction.java]: Could be final.

File: exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java [hunk 4]
```diff
@@ -59,12 +60,16 @@ public int size() {
     }
 
     @Override
-    public AbstractMapType remove(AtomicValue key) {
-        try {
+    public AbstractMapType remove(AtomicValue[] keysAtomicValues) throws XPathException {
```
Comment (adamretter) [inline exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java]: Parameter could be final

File: exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java [hunk 5]
```diff
@@ -59,12 +60,16 @@ public int size() {
...
+        for (final AtomicValue key: keysAtomicValues) {
+            if (key != this.key) { continue; }
```
Comment (adamretter) [inline exist-core/src/main/java/org/exist/xquery/functions/map/SingleKeyMapType.java]: Multi-line.

**Comment by joewiz** [comment]
Excellent! Thanks @line-o, and thanks, @dizzzz and @adamretter!
