### PR TITLE
(4.x.x) Repair output JMX servlet to contain all eXist-db specific information.

### LINKED ISSUE #2118: JMX servlet does not contain eXist-db specific information
### What is the problem
The url http://localhost:8080/exist/status does not return all required information for the Monex app. As a result the Monex app does not work as expected.

in logging:

```
2018-08-16 10:25:52,196 [main] WARN  (AgentFactory.java [getInstance]:46) - Failed to instantiate class for JMX agent: org.exist.management.impl.JMXAgent 
```

with debugger

```
java.lang.IllegalAccessException: Class org.exist.management.AgentFactory can not access a member of class org.exist.management.impl.JMXAgent with modifiers "private"
```

image

### What did you expect
The XML file should contain the sections as defined in `org/exist/management/impl/JMXAgent.java`

### Describe how to reproduce or add a test
- Start monex
- retrieve XML via URL

### Context information

- eXist-db version : 4.x.x / 24ec68348bcd7854d65b75c396de3acdfbd2932a
- Java version (e.g. Java8u121) // java8U172
- Operating system (Windows 7, Linux, MacOs) / windows
- 32 or 64 bit / 64
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub) / clone
- Any custom changes in e.g. conf.xml / nope

### PR DESCRIPTION
**Pull request by dizzzz**
- Repair output JMX servlet to contain all eXist-db specific information.
- Fixes #2118
- added unit tests
- verified Monex to work again

### CODE REVIEW

File: test/src/org/exist/management/JmxRemoteTest.java [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+        assertThat(jmxXML, hasXPath("//jmx:WebAppContext").withNamespaceContext(prefix2Uri));
+
+        // eXist-db
+        assertThat(jmxXML, hasXPath("//jmx:ProcessReport").withNamespaceContext(prefix2Uri));
+        assertThat(jmxXML, hasXPath("//jmx:Cache").withNamespaceContext(prefix2Uri));
+        assertThat(jmxXML, hasXPath("//jmx:SystemInfo").withNamespaceContext(prefix2Uri));
+        assertThat(jmxXML, hasXPath("//jmx:CacheManager").withNamespaceContext(prefix2Uri));
+        assertThat(jmxXML, hasXPath("//jmx:LockManager").withNamespaceContext(prefix2Uri));
+        assertThat(jmxXML, hasXPath("//jmx:SanityReport").withNamespaceContext(prefix2Uri));
+        assertThat(jmxXML, hasXPath("//jmx:Database").withNamespaceContext(prefix2Uri));
```
Comment (duncdrum) [inline test/src/org/exist/management/JmxRemoteTest.java]: can i suggest adding a check for `jmx:DiskUsage` which is currently part of 4.3.1 but not 5.0.0-RC3
