### PR TITLE
[bugfix] NPE on predicates with an empty sequence

### LINKED ISSUE #3797: [BUG] NPE on empty sequence in predicate
**Describe the bug**

The following XQuery leads to a NullPointerException `(1)[()]`

**Expected behavior**

If this is an error, an exception with a meaningful error message and location date should be thrown.

**To Reproduce**

evaluate the XQuery snippet above

**Context (please always complete the following information):**
 - eXist-db version: latest develop 4415b13d
 - Java Version recent Adopt Open JDK 8

**Additional context**
- How is eXist-db installed? built from source
- Any custom changes in e.g. `conf.xml`? none

### PR DESCRIPTION
**Pull request by line-o**
### Description:

If the inner sequence in a predicate evaluates to an empty sequence, an empty sequence is returned.

### Reference:

fixes #3797

Saxon 10 HE and BaseX 9.5 as well as eXist-db versions > 5.3.0-SNAPSHOT all have this behaviour.

@dizzzz showed in #3800 a nicer condition with `Sequence#isEmpty` so I incorporated that.

### Type of tests:

Several tests added to positional.xql XQSuite

### CODE REVIEW

**Comment by line-o** [comment]
XQTS test result

Tests | Failures | Errors | Skipped | Success rate | Time
-- | -- | -- | -- | -- | --
31557 | 5161 | 563 | 1260 | 81.86% | 1345.101

File: exist-core/src/main/java/org/exist/xquery/Predicate.java [hunk 1]
```diff
@@ -194,9 +194,13 @@ public Sequence evalPredicate(final Sequence outerSequence,
...
                                 ? contextSequence : null);
                     }
-                    if (innerSeq.getCardinality().isSubCardinalityOrEqualOf(Cardinality.EXACTLY_ONE)) {
+
+                    if (innerSeq.getCardinality().equals(Cardinality.EMPTY_SEQUENCE)) {
+                        result = Sequence.EMPTY_SEQUENCE;
+                    } else if (innerSeq.getCardinality().isSubCardinalityOrEqualOf(Cardinality.EXACTLY_ONE)) {
                         result = selectByPosition(outerSequence, contextSequence, mode, innerSeq);
-                    } else {
+                    }
```
Comment (dizzzz) [inline exist-core/src/main/java/org/exist/xquery/Predicate.java:202]: formatting is not ok?

File: exist-core/src/main/java/org/exist/xquery/Predicate.java [hunk 2]
```diff
@@ -194,9 +194,13 @@ public Sequence evalPredicate(final Sequence outerSequence,
                         innerSeq = inner.eval(Dependency.dependsOn(inner.getDependencies(), Dependency.CONTEXT_ITEM)
                                 ? contextSequence : null);
                     }
-                    if (innerSeq.getCardinality().isSubCardinalityOrEqualOf(Cardinality.EXACTLY_ONE)) {
+
+                    if (innerSeq.getCardinality().equals(Cardinality.EMPTY_SEQUENCE)) {
```
Comment (dizzzz) [inline exist-core/src/main/java/org/exist/xquery/Predicate.java:198]: in essence I have the same check...... I think.

File: exist-core/src/main/java/org/exist/xquery/Predicate.java (hunk 1 above)
Comment (line-o) [reply exist-core/src/main/java/org/exist/xquery/Predicate.java:202]: It depends, I would write all else blocks that way. The implicit coding style of eXist-db is different, though. I will change that.

File: exist-core/src/main/java/org/exist/xquery/Predicate.java (hunk 2 above)
Comment (line-o) [reply exist-core/src/main/java/org/exist/xquery/Predicate.java:198]: Are you sure `isEmpty()` works the way we think it does? @dizzzz

Comment (line-o) [reply exist-core/src/main/java/org/exist/xquery/Predicate.java]: I checked, it is exactly what we want :)

**Review by dizzzz — APPROVED** [review]
