### PR TITLE
make sure that functionDef do not shared between DeferredFunctionCallImpl

### LINKED ISSUE #758: Error in nested fn:fold-left call
The following code returns the wrong result:

``` xquery
xquery version "3.1";

declare function local:join($value){
    let $args := 
        array:for-each($value("args"),function($_){
            if($_ instance of map(xs:string, item()?)) then
                local:join($_)
            else
                $_
        })
    let $args2 :=
        array:fold-left($args,[],function($pre,$cur){
            array:append($pre,$cur)
        })
    return
        string-join(array:flatten($args2),",")
};

let $map := map { 
    "args" := [
        "'a'",
        map {
            "args":=["'x'","'y'"]
        },
        "'b'"]
}
return local:join($map)
```

The result should read `'a','x','y','b'` but instead it's `'a','x','x','b'`

### PR DESCRIPTION
**Pull request by shabanovd**
close #758

### CODE REVIEW

File: src/org/exist/xquery/FunctionCall.java [hunk 1]
```diff
@@ -362,15 +362,20 @@ public void accept(ExpressionVisitor visitor) {
         visitor.visitFunctionCall(this);
     }
 
-    private class DeferredFunctionCallImpl extends DeferredFunctionCall {
+    private static class DeferredFunctionCallImpl extends DeferredFunctionCall {
```
Comment (dizzzz) [inline src/org/exist/xquery/FunctionCall.java]: are you sure this inner class should be static?

Comment (shabanovd) [inline src/org/exist/xquery/FunctionCall.java]: yeap, it was design bug to not make it static

Comment (adamretter) [inline src/org/exist/xquery/FunctionCall.java]: @dizzzz Inner classes should always be `static` unless they explicitly and directly and need access to the outer classes variable members.

However, that said, the approach @shabanovd is taking looks wrong here to me. He explicitly passed the outer class because he needs access to the members. I think it is better to either:

1) Not make the inner class static.
2) Make the inner class static, but do not access the member variables directly, instead call the accessor functions, then these could be mocked for testing. i.e. instead of `call.mySignature` use `call.getSignature()`

Comment (adamretter) [inline src/org/exist/xquery/FunctionCall.java]: My preference would like be for (1) as that means less change and that was working before.

Comment (shabanovd) [inline src/org/exist/xquery/FunctionCall.java]: @adamretter you did not understand the problem and the solution I provide. Please, spend a bit of time to thinking before write proposal. [Point by finger](https://github.com/eXist-db/exist/pull/1271/files/ee056ce36d5885ba5effde23a9bccd1cc5b67854#diff-f2b23bccdd5042ec21691c3e7464d672R443)

That is `private static`, so I do not any issue to access `parent` class variable directly.

**Comment by adamretter** [comment]
@shabanovd @wolfgangmm Okay, sounds good, I would suggest that we move the inner class out. So that it is a standalone class in its own right.

File: src/org/exist/xquery/FunctionCall.java (hunk 1 above)
Comment (adamretter) [inline src/org/exist/xquery/FunctionCall.java]: I see, still looks weird to me, see my comment below. I think it best to make this a non-inner class now.

**Comment by shabanovd** [comment]
@adamretter that is only place where this class is used, so I prefer to keep code together.

**Comment by adamretter** [comment]
Travis is reporting test failures though - could you take a look please?

**Comment by shabanovd** [comment]
@adamretter how to rerun travis?

**Comment by adamretter** [comment]
@shabanovd If you visit the Travis build - https://travis-ci.org/eXist-db/exist/builds/203607846
You should see a button near the top left which says "Restart Build"

**Comment by shabanovd** [comment]
@adamretter [this](https://github.com/eXist-db/exist/blob/005045fda2ee0df0c3871b12d1b90a79f086ffbc/test/src/org/exist/xquery/DeferredFunctionCallTest.java#L110) is failing. It's much harder to read than actual code and I have no idea how to fix it.

**Comment by shabanovd** [comment]
@adamretter fixed
