### PR TITLE
Handle IllegalStateException in `file:directory-list#2`

### LINKED ISSUE #5028: [BUG] file:directory-list#2 does not properly report an error on a non-existent directory
**Describe the bug**
The Java code of `DirectoryList` throws an `IllegalStateException` when a non-existent directory is supplied as its first argument, which is an unchecked exception and therefore not caught in Java. From Oxygen, this results in a `Failed to invoke method queryPT in class org.exist.xmlrpc.RpcConnection:` message.

**Expected behavior**
We expect an XQuery error to be thrown with module, line number and column information.

**To Reproduce**
Assuming a non-existent path `/foo` run the following : 
`file:directory-list('/foo', '*')`

 - Build: [eXist-6.2.0]
 - Java: [1.8.0_347]
 - OS:  Windows 10

### PR DESCRIPTION
**Pull request by line-o**
Closes #5028

The Java code of DirectoryList can throw an IllegalStateException when a non-existent directory is supplied as its first argument. This exception class is now handled in file:list#2.

This is a forward port of #5061 
Thanks to @nverwer for bringing this up and also finding the fix.

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]

**Review by reinhapa — APPROVED** [review]

**Comment by line-o** [comment]
We should consider adding a test for this.

```
file:directory-list('/non/existent', ())
```

**Review by adamretter — CHANGES_REQUESTED** [review]
As @line-o suggested, let's add a test...

**Comment by line-o** [comment]
Test added

**Comment by line-o** [comment]
6.x.x backport is #5093

**Review by dizzzz — APPROVED** [review]

File: extensions/modules/file/src/main/java/org/exist/xquery/modules/file/FileErrorCode.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ */
+package org.exist.xquery.modules.file;
+
+import org.exist.dom.QName;
+import org.exist.xquery.ErrorCodes;
+
+class FileErrorCode extends ErrorCodes.ErrorCode {
+    public static final ErrorCodes.ErrorCode DIRECTORY_NOT_FOUND = new FileErrorCode("DIRECTORY_NOT_FOUND", "The directory could not be found.");
+
+    FileErrorCode(String code, String description) {
```
Comment (adamretter) [inline extensions/modules/file/src/main/java/org/exist/xquery/modules/file/FileErrorCode.java:30]: There parameters could be set `final`.

**Review by adamretter — COMMENTED** [review]
1 comment otherwise this LGTM.

File: extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java [hunk 2]
```diff
@@ -34,11 +33,7 @@
 import org.exist.dom.QName;
 import org.exist.dom.memtree.MemTreeBuilder;
 import org.exist.util.FileUtils;
-import org.exist.xquery.BasicFunction;
-import org.exist.xquery.Cardinality;
-import org.exist.xquery.FunctionSignature;
-import org.exist.xquery.XPathException;
-import org.exist.xquery.XQueryContext;
+import org.exist.xquery.*;
```
Comment (reinhapa) [inline extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java:36]: Do we not prefer single line imports?

**Review by reinhapa — CHANGES_REQUESTED** [review]

File: extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java (hunk 2 above)
Comment (line-o) [reply extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java:36]: We do not enforce this consistently.

**Review by reinhapa — APPROVED** [review]

File: extensions/modules/file/src/main/java/org/exist/xquery/modules/file/FileErrorCode.java (hunk 1 above)
Comment (line-o) [reply extensions/modules/file/src/main/java/org/exist/xquery/modules/file/FileErrorCode.java]: done

**Review by adamretter — APPROVED** [review]
Thanks for addressing the code review, now LGTM.

**Comment by PieterLamers** [comment]
Thanks everybody!
