### PR TITLE
XSL stylesheet caching and compiling bugfixes

### LINKED ISSUE #1312: calls to doc() in an XSLTSerlvet context executed within the database throw URIResolver errors
### What is the problem
When called in an XSLT stylesheet, which is executed via XSLTServlet within the database, the `doc()` function fails with following error:

    SAX exception while transforming node: Exception thrown by URIResolver

Yet, the URI does resolve, and the same XSLT stylesheet is working without errors when called with the `transform:transform()` function, and when executed via XSLTServlet on the file system.

Moreover, **execution order** seems to matter (see below).

### What did you expect

In the sample app (see below), I'd expect the call to `doc('http://localhost:8080/exist/apps/doc-test/test.xml')` to be resolved properly, and to get following output from the simple XSLT stylesheet, irrespective of the execution context / order: 

    <xslt-output><h1>doc() has succeeded!</h1></xslt-output>

### Describe how to reproduce or add a test
The zip file attached [doc-test.zip](https://github.com/eXist-db/exist/files/814514/doc-test.zip) contains a sample web application demonstrating the problem, which can be reproduced by following steps:

1. install the `doc-test-0.1.xar` file in the database
2. navigate to http://localhost:8080/exist/apps/doc-test/test-XSLTServlet/

This will cause an HTTP ERROR 500, stating that 

> An error occurred: SAX exception while transforming node: Exception thrown by URIResolver

Additional remarks: 

#### 1. execution context matters
The error only occurs when the XSLT transformation is executed via XSLTServlet within the database.

- If the same XSLT transformation is executed via the `transform:transform()`  function in an XQuery script stored in the database, it succeeds without errors. See http://localhost:8080/exist/apps/doc-test/test-transform/ for an example.
- If the same XSLT transformation is executed via XSLTServlet on the file system, it succeeds without errors. See http://localhost:8080/exist/doc-test/test-XSLTServlet/ for an example (this requires that the zip file is extracted in the `${exist.home}/webapps/` directory.

#### 2. execution order matters
The error occurs when the XSLT transformation is executed via XSLTServlet within the database, but once the same transformation is executed via the `transform:transform()`  function in an XQuery script stored in the database, subsequent executions via XSLTServlet succeed without errors. See following steps:

1. Execute via XSLTServlet: http://localhost:8080/exist/doc-test/test-XSLTServlet/ --> error
2. Execute via `transform:transform()`: http://localhost:8080/exist/apps/doc-test/test-transform/ --> success
3. Execute via XSLTServlet: http://localhost:8080/exist/doc-test/test-XSLTServlet/ --> **success**

Since this error doesn't occur in eXist-3.0.RC1 (nor in eXist-3.0.RC2, although that version is giving me troubles with local paths to `doc()` that I couldn't reproduce, unfortunately), I suspect that it might be related to the issues that have been addressed recently in https://github.com/eXist-db/exist/pull/1221.

### Context information
- eXist-db version: 3.0 /  acd0c14
- Java: 1.8.0_112
- Operating system: Windows 7
- 64 bit
- No custom changes

### PR DESCRIPTION
**Pull request by shabanovd**
### Description:
inline xsl stylesheets caching and compiling between XSLTServlet and xquery `transform` function;
[bugfix] avoid concurrent use of different variables: DBBroker, ErrorListener, SAXTransformerFactory (and it attributes).

### Reference:
close #1312

### CODE REVIEW

**Comment by dizzzz** [comment]
wow..... that is a fast fix!

**Comment by dizzzz** [comment]
```
BUILD FAILED
/home/travis/build/eXist-db/exist/build/scripts/junit.xml:124: Test org.exist.xslt.TransfomerFactoryAllocatorTest failed
```

**Comment by shabanovd** [comment]
@dizzzz that is huge fix for sure. There was so many concurrent bugs and code copies. That's why I decided to refactor it ;-)

**Comment by shabanovd** [comment]
@dizzzz fixed

File: src/org/exist/xquery/functions/transform/EXistURIResolver.java [hunk 1]
```diff
@@ -43,134 +43,136 @@
...
-        }
+    final int numPathComponents = Array.getLength(pathComponents);
+    final String[] simplifiedComponents = new String[numPathComponents];
+    int numSimplifiedComponents = 0;
 
-        if (path.endsWith("/")) {
-            b.append("/");
-        }
+    for(final String s : pathComponents) {
+      if (s.length() == 0) {continue;}		// Remove empty elements ("//")
```
Comment (dizzzz) [inline src/org/exist/xquery/functions/transform/EXistURIResolver.java]: s.isEmpty()

File: src/org/exist/xquery/functions/transform/EXistURIResolver.java [hunk 2]
```diff
@@ -43,134 +43,136 @@
...
+      if (".".equals(s)) {continue;}		// Remove identity elements ("/./")
+      if ("..".equals(s)) {				// Remove parent elements ("/../") unless at the root
+        if (numSimplifiedComponents > 0) {numSimplifiedComponents--;}
```
Comment (dizzzz) [inline src/org/exist/xquery/functions/transform/EXistURIResolver.java]: reformat

File: src/org/exist/xslt/EXistURIResolver.java [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+        }
+
+        final String[] pathComponents = path.substring(1).split("/");
+
+        final int numPathComponents = Array.getLength(pathComponents);
+        final String[] simplifiedComponents = new String[numPathComponents];
+        int numSimplifiedComponents = 0;
+
+        for(final String s : pathComponents) {
+            if (s.length() == 0) {continue;}		// Remove empty elements ("//")
```
Comment (dizzzz) [inline src/org/exist/xslt/EXistURIResolver.java]: double code; s.isEMpty()

File: src/org/exist/xslt/EXistURIResolver.java [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+
+        if (href.isEmpty()) {
+            path = base;
+        } else {
+            URI hrefURI = null;
+            try {
+                hrefURI = new URI(href);
+            } catch (final URISyntaxException e) {
+            }
+            if (hrefURI != null && hrefURI.isAbsolute()) {
```
Comment (dizzzz) [inline src/org/exist/xslt/EXistURIResolver.java]: double code?

File: src/org/exist/xslt/StylesheetUri.java [hunk 5]
```diff
@@ -0,0 +1,189 @@
...
+  String uri;
+  String base;
+
+  Properties properties;
+
+  public StylesheetUri(String uri) {
+    this.uri = uri;
+
+    final int p = uri.lastIndexOf("/");
+    if (p != Constants.STRING_NOT_FOUND) {
```
Comment (dizzzz) [inline src/org/exist/xslt/StylesheetUri.java]: you can use Java6' String.contains()

File: src/org/exist/xslt/StylesheetUri.java [hunk 6]
```diff
@@ -0,0 +1,189 @@
...
+
+    return handler;
+  }
+
+  private <E extends Exception> Templates compileTemplates(
+      DBBroker broker,
+      DocumentImpl stylesheet,
+      XSLTErrorsListener<E> errorListener)
+      throws E, TransformerConfigurationException, SAXException
+  {
```
Comment (dizzzz) [inline src/org/exist/xslt/StylesheetUri.java]: please reformat

File: src/org/exist/xslt/StylesheetUri.java [hunk 7]
```diff
@@ -0,0 +1,189 @@
...
+    return t;
+  }
+
+  private SAXTransformerFactory cachedFactory(BrokerPool db) {
+    if (factory == null) {
+      factory = TransformerFactoryAllocator.getTransformerFactory(db);
+
+      if (properties != null) {
+        //set any attributes
+        for (final Map.Entry<Object, Object> attribute : properties.entrySet()) {
```
Comment (dizzzz) [inline src/org/exist/xslt/StylesheetUri.java]: candidate for lambda expression

File: src/org/exist/xslt/TemplatesFactory.java [hunk 8]
```diff
@@ -0,0 +1,151 @@
...
+          uri = f.toUri().toASCIIString();
+        }
+      }
+    }
+    return uri;
+  }
+
+  public static <E extends Exception> Stylesheet stylesheet(DBBroker broker, NodeValue node, String baseUri)
+      throws E, TransformerConfigurationException
+  {
```
Comment (dizzzz) [inline src/org/exist/xslt/TemplatesFactory.java]: reformat

File: src/org/exist/xslt/XSLTErrorsListener.java [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+import org.apache.logging.log4j.Logger;
+
+/**
+ * @author <a href="mailto:shabanovd@gmail.com">Dmitriy Shabanov</a>
+ */
+public abstract class XSLTErrorsListener<E extends Exception> implements ErrorListener {
+
+  private final static Logger LOG = LogManager.getLogger(XSLTErrorsListener.class);
+
+  private final static int NO_ERROR = 0;
```
Comment (dizzzz) [inline src/org/exist/xslt/XSLTErrorsListener.java]: would it make sense to convert this to an enum?

File: src/org/exist/xquery/functions/transform/EXistURIResolver.java [hunk 10]
```diff
@@ -43,134 +43,136 @@
...
 
-        return b.toString();
+    if (numSimplifiedComponents == 0) {
+      return "/";
     }
 
-    @Override
-    public Source resolve(final String href, String base) throws TransformerException {
-        String path;
+    final StringBuilder b = new StringBuilder(path.length());
```
Comment (dizzzz) [inline src/org/exist/xquery/functions/transform/EXistURIResolver.java]: b .... maybe a descriptive name of what will be in the buffer?

File: src/org/exist/xquery/functions/transform/EXistURIResolver.java (hunk 2 above)
Comment (shabanovd) [inline src/org/exist/xquery/functions/transform/EXistURIResolver.java]: EXistURIResolver is old code

File: src/org/exist/xslt/EXistURIResolver.java (hunk 3 above)
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: EXistURIResolver is old code

File: src/org/exist/xslt/EXistURIResolver.java (hunk 4 above)
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: EXistURIResolver is old code

File: src/org/exist/xquery/functions/transform/EXistURIResolver.java (hunk 1 above)
Comment (shabanovd) [inline src/org/exist/xquery/functions/transform/EXistURIResolver.java]: that is old code that I put back as `deprecated`

File: src/org/exist/xquery/functions/transform/EXistURIResolver.java (hunk 2 above)
Comment (shabanovd) [inline src/org/exist/xquery/functions/transform/EXistURIResolver.java]: that is old code that I put back as `deprecated`

File: src/org/exist/xslt/XSLTErrorsListener.java (hunk 9 above)
Comment (shabanovd) [inline src/org/exist/xslt/XSLTErrorsListener.java]: that is for internal use only

File: src/org/exist/xquery/functions/transform/EXistURIResolver.java (hunk 10 above)
Comment (shabanovd) [inline src/org/exist/xquery/functions/transform/EXistURIResolver.java]: that is old code, rename to`sb` if you like?

File: src/org/exist/xslt/TemplatesFactory.java (hunk 8 above)
Comment (shabanovd) [inline src/org/exist/xslt/TemplatesFactory.java]: I did, that is formatted code. What do you think wrong?

**Comment by shabanovd** [comment]
@dizzzz that is not duplicate code (pay attention to commits description -)
The duplicate code required to make it to 3.1.0, without that `deprecated` class it must go to 4.0.0 only.

File: src/org/exist/xslt/StylesheetUri.java (hunk 5 above)
Comment (shabanovd) [inline src/org/exist/xslt/StylesheetUri.java]: That is not possible because `p` required for `uri.substring(0, p);`

File: src/org/exist/xslt/StylesheetUri.java (hunk 7 above)
Comment (shabanovd) [inline src/org/exist/xslt/StylesheetUri.java]: why?

**Comment by shabanovd** [comment]
@dizzzz EXistURIResolver reformatted

File: src/org/exist/xslt/StylesheetUri.java (hunk 7 above)
Comment (dizzzz) [inline src/org/exist/xslt/StylesheetUri.java]: no specific reason :-)

File: src/org/exist/xslt/TemplatesFactory.java (hunk 8 above)
Comment (dizzzz) [inline src/org/exist/xslt/TemplatesFactory.java]: the { is on the wrong line?

File: extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java [hunk 11]
```diff
@@ -126,7 +126,9 @@ private FOUserAgent setupFOUserAgent(final FOUserAgent foUserAgent, final Proper
      */
     private ResourceResolver getResourceResolver(final DBBroker broker, final String baseUri) {
         final ResourceResolverFactory.SchemeAwareResourceResolverBuilder builder = ResourceResolverFactory.createSchemeAwareResourceResolverBuilder(ResourceResolverFactory.createDefaultResourceResolver());
-        final URIResolverAdapter uriResolver = new URIResolverAdapter(new ExistSchemeRewriter(new EXistURIResolver(broker, baseUri)));
+        final URIResolverAdapter uriResolver = new URIResolverAdapter(
+            new ExistSchemeRewriter(new EXistURIResolver(broker.getBrokerPool(), baseUri))
+        );
         builder.registerResourceResolverForScheme("exist", uriResolver);
```
Comment (dizzzz) [inline extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java]: xmldb: ??

Comment (shabanovd) [inline extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java]: that is not my code or code this PR. If you want to address this issue open new PR for it

**Comment by shabanovd** [comment]
@dizzzz there is already [test](https://github.com/eXist-db/exist/pull/1316/files#diff-ede73efa2260d94d3434c2b656b4ab5fR36) for it

File: extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java (hunk 11 above)
Comment (dizzzz) [inline extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java]: sorry my remark is a bit lower: 'exist' is registered, should this be 'xmldb' ? or both?

Comment (shabanovd) [inline extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java]: @dizzzz better to ask @adamretter why it here at all. He did point [here](https://github.com/eXist-db/exist/pull/1340) that we did/should not use `exist:///`, so this must cleaned up.

If you want it to be fixed open issue for it (to remember).

File: src/org/exist/xslt/TemplatesFactory.java [hunk 12]
```diff
@@ -0,0 +1,151 @@
...
+
+    return new StylesheetUri(uri, properties);
+  }
+
+  private static Stylesheet stylesheet(String stylesheet, String baseUri) {
+
+    String uri = uri(stylesheet, baseUri);
+
+    cache.computeIfAbsent(uri, StylesheetUri::new);
+    return cache.get(uri);
```
Comment (adamretter) [inline src/org/exist/xslt/TemplatesFactory.java]: Just `return cache.computeIfAbsent(uri, StylesheetUri::new);`

File: src/org/exist/xslt/StylesheetUri.java [hunk 13]
```diff
@@ -0,0 +1,189 @@
...
+
+    final Templates t = handler.getTemplates();
+
+    //check for errors
+    errorListener.checkForErrors();
+
+    return t;
+  }
+
+  private SAXTransformerFactory cachedFactory(BrokerPool db) {
```
Comment (adamretter) [inline src/org/exist/xslt/StylesheetUri.java]: It seems to me this is used concurrently from `TemplatesFactory` so you will need synchronization on the cached `factory` and the mutable class members.

File: src/org/exist/xslt/TemplatesFactory.java [hunk 14]
```diff
@@ -0,0 +1,151 @@
...
+import org.exist.security.PermissionDeniedException;
+import org.exist.storage.DBBroker;
+import org.exist.xquery.Constants;
+import org.exist.xquery.value.NodeValue;
+import org.w3c.dom.Document;
+import org.xml.sax.SAXException;
+
+/**
+ * @author <a href="mailto:shabanovd@gmail.com">Dmitriy Shabanov</a>
+ */
```
Comment (adamretter) [inline src/org/exist/xslt/TemplatesFactory.java]: Please add the `@ThreadSafe` JCIP annotation if your intention is that this class is thread safe

File: src/org/exist/xslt/TemplatesFactory.java [hunk 15]
```diff
@@ -0,0 +1,151 @@
...
+      if (uri != null) {
+        base = uri.substring(0, uri.lastIndexOf('/'));
+      }
+    }
+
+    if (base != null) {
+      factory.setURIResolver(new EXistURIResolver(broker.getBrokerPool(), base));
+    }
+
+    return new Stylesheet() {
```
Comment (adamretter) [inline src/org/exist/xslt/TemplatesFactory.java]: I don't like this overriding the class inline. I think you should create a proper sub-class

File: src/org/exist/xslt/TransformerFactoryAllocator.java [hunk 16]
```diff
@@ -75,21 +73,6 @@ private TransformerFactoryAllocator() {
      * TransformerFactoryAllocator.getTransformerFactory(broker).newInstance()
      */
     public static SAXTransformerFactory getTransformerFactory(final BrokerPool pool) {
```
Comment (adamretter) [inline src/org/exist/xslt/TransformerFactoryAllocator.java]: Why can't we reuse a single TransformerFactory instance?

File: src/org/exist/xslt/XSLTErrorsListener.java (hunk 9 above)
Comment (adamretter) [inline src/org/exist/xslt/XSLTErrorsListener.java]: Even for private use an Enum has advantages.

File: src/org/exist/xslt/XSLTErrorsListener.java [hunk 17]
```diff
@@ -0,0 +1,93 @@
...
+  private final static int WARNING = 1;
+  private final static int ERROR = 2;
+  private final static int FATAL = 3;
+
+  boolean stopOnError;
+  boolean stopOnWarn;
```
Comment (adamretter) [inline src/org/exist/xslt/XSLTErrorsListener.java]: These should not be `package private`. Also they should be `final`.

File: src/org/exist/xslt/XSLTErrorsListener.java [hunk 18]
```diff
@@ -0,0 +1,93 @@
...
+
+  private int errorCode = NO_ERROR;
+  private Exception exception;
+
+  public XSLTErrorsListener(boolean stopOnError, boolean stopOnWarn) {
```
Comment (adamretter) [inline src/org/exist/xslt/XSLTErrorsListener.java]: `final` arguments please

File: src/org/exist/xslt/XSLTErrorsListener.java [hunk 19]
```diff
@@ -0,0 +1,93 @@
...
+    LOG.warn("XSL transform reports recoverable error: " + except.getMessage(), except);
+    errorCode = ERROR;
+    exception = except;
+    if (stopOnError) {
+      throw except;
+    }
+  }
+
+  public void fatalError(TransformerException except) throws TransformerException {
+    LOG.warn("XSL transform reports fatal error: " + except.getMessage(), except);
```
Comment (adamretter) [inline src/org/exist/xslt/XSLTErrorsListener.java]: Should be `LOG.error`

File: src/org/exist/xslt/XSLTErrorsListener.java [hunk 20]
```diff
@@ -0,0 +1,93 @@
...
+    LOG.warn("XSL transform reports warning: " + except.getMessage(), except);
+    errorCode = WARNING;
+    exception = except;
+    if (stopOnWarn) {
+      throw except;
+    }
+  }
+
+  public void error(TransformerException except) throws TransformerException {
+    LOG.warn("XSL transform reports recoverable error: " + except.getMessage(), except);
```
Comment (adamretter) [inline src/org/exist/xslt/XSLTErrorsListener.java]: Should be `LOG.error`

File: src/org/exist/http/servlets/XSLTServlet.java [hunk 21]
```diff
@@ -104,9 +91,17 @@
 
     private final static Logger LOG = LogManager.getLogger(XSLTServlet.class);
 
+    private final static XSLTErrorsListener<ServletException> errorListener =
+        new XSLTErrorsListener<ServletException>(true, false) {
+
+            @Override
+            protected void raiseError(String error, Exception ex) throws ServletException {
```
Comment (adamretter) [inline src/org/exist/http/servlets/XSLTServlet.java]: `final` arguments please

File: src/org/exist/http/servlets/XSLTServlet.java [hunk 22]
```diff
@@ -104,9 +91,17 @@
 
     private final static Logger LOG = LogManager.getLogger(XSLTServlet.class);
 
+    private final static XSLTErrorsListener<ServletException> errorListener =
+        new XSLTErrorsListener<ServletException>(true, false) {
```
Comment (adamretter) [inline src/org/exist/http/servlets/XSLTServlet.java]: Diamond syntax please

File: src/org/exist/http/servlets/XSLTServlet.java [hunk 23]
```diff
@@ -306,9 +296,8 @@ else if (mediaType.indexOf("charset") == -1) {
     /*
      * Please add comments to this method. make assumption clear. These might not be valid.
      */
-    private Templates getSource(Subject user, HttpServletRequest request, HttpServletResponse response,
-                                SAXTransformerFactory factory, String stylesheet)
-            throws ServletException, IOException {
+    private Stylesheet stylesheet(String stylesheet, HttpServletRequest request, HttpServletResponse response)
```
Comment (adamretter) [inline src/org/exist/http/servlets/XSLTServlet.java]: `final` arguments please

File: src/org/exist/http/servlets/XSLTServlet.java [hunk 24]
```diff
@@ -348,26 +337,7 @@ private Templates getSource(Subject user, HttpServletRequest request, HttpServle
...
-            LOG.debug("Loading stylesheet from " + stylesheet);
-        }
-
-        CachedStylesheet cached = cache.get(stylesheet);
-        if (cached == null) {
-            cached = new CachedStylesheet(factory, user, stylesheet, base);
-            cache.put(stylesheet, cached);
-        }
-        return cached.getTemplates(user);
+        return TemplatesFactory.stylesheet(stylesheet, "", isCaching());
```
Comment (adamretter) [inline src/org/exist/http/servlets/XSLTServlet.java]: I think you should use `null` and not an empty string and then add `@Nullable` to the method argument.

File: src/org/exist/xquery/functions/transform/Transform.java [hunk 25]
```diff
@@ -208,10 +190,16 @@ public Sequence eval(Sequence[] args, Sequence contextSequence) throws XPathExce
                 "yes".equals(serializationProps.getProperty(EXistOutputKeys.EXPAND_XINCLUDES, "yes"));
 
 
+        final XSLTErrorsListener<XPathException> errorListener =
+            new XSLTErrorsListener<XPathException>(stopOnError, stopOnWarn) {
+                @Override
+                protected void raiseError(String error, Exception ex) throws XPathException {
```
Comment (adamretter) [inline src/org/exist/xquery/functions/transform/Transform.java]: `final` arguments please

File: src/org/exist/xquery/functions/transform/Transform.java [hunk 26]
```diff
@@ -360,71 +348,75 @@ public Sequence eval(Sequence[] args, Sequence contextSequence) throws XPathExce
      * @throws TransformerFactoryConfigurationError
      * @throws XPathException
      */
-    private TransformerHandler createHandler(Item stylesheetItem, Properties options, Properties attributes) throws TransformerFactoryConfigurationError, XPathException {
-        final SAXTransformerFactory factory = TransformerFactoryAllocator.getTransformerFactory(context.getBroker().getBrokerPool());
-
-        //set any attributes
-        for (final Map.Entry<Object, Object> attribute : attributes.entrySet()) {
-            factory.setAttribute((String) attribute.getKey(), attribute.getValue());
+    private TransformerHandler createHandler(
```
Comment (adamretter) [inline src/org/exist/xquery/functions/transform/Transform.java]: Fix the formatting here please

Comment (adamretter) [inline src/org/exist/xquery/functions/transform/Transform.java]: Also `final` arguments please

File: src/org/exist/xquery/functions/transform/Transform.java [hunk 27]
```diff
@@ -360,71 +348,75 @@ public Sequence eval(Sequence[] args, Sequence contextSequence) throws XPathExce
...
+        XSLTErrorsListener<XPathException> errorListener
+    )
+        throws TransformerFactoryConfigurationError, XPathException
+    {
+
+        boolean useCache = true;
+        final Object property = context.getBroker().getConfiguration().getProperty(TransformerFactoryAllocator.PROPERTY_CACHING_ATTRIBUTE);
+        if (property != null) {
+            useCache = (Boolean) property;
         }
```
Comment (adamretter) [inline src/org/exist/xquery/functions/transform/Transform.java]:
```
final Object property = context.getBroker().getConfiguration().getProperty(TransformerFactoryAllocator.PROPERTY_CACHING_ATTRIBUTE);
final boolean useCache = property != null && (Boolean)property;
```

File: src/org/exist/xquery/functions/transform/Transform.java [hunk 28]
```diff
@@ -360,71 +348,75 @@ public Sequence eval(Sequence[] args, Sequence contextSequence) throws XPathExce
...
-            handler = factory.newTransformerHandler(templates);
+
+            handler = stylesheet.newTransformerHandler(getContext().getBroker(), errorListener);
 
             if (options != null) {
                 setParameters(options, handler.getTransformer());
             }
 
-        } catch (final TransformerConfigurationException e) {
+        } catch (final Exception e) {
```
Comment (adamretter) [inline src/org/exist/xquery/functions/transform/Transform.java]: I would prefer not to blanket catch `Exception`

File: extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java (hunk 11 above)
Comment (shabanovd) [inline extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java]: @adamretter @dizzzz that is exactly reason why I'm pushing `xmldb:/` (as developer independent protocol for in db uri/url reference)

File: src/org/exist/xslt/EXistURIResolver.java [hunk 29]
```diff
@@ -0,0 +1,201 @@
...
+
+  public EXistURIResolver(final BrokerPool db, final String docPath) {
+    this.db = db;
+    this.basePath = normalize(docPath);
+    if (LOG.isDebugEnabled()) {
+      LOG.debug("EXistURIResolver base path set to " + basePath);
+    }
+  }
+
+  private String normalize(String uri) {
```
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: @adamretter I'm going to ignore your requests to use `final` because that is your coding style, not mine

File: src/org/exist/xslt/EXistURIResolver.java [hunk 30]
```diff
@@ -0,0 +1,201 @@
...
+   * Simplify a path removing any "." and ".." path elements.
+   * Assumes an absolute path is given.
+   */
+  private String normalizePath(final String path) {
+    if (!path.startsWith("/")) {
+      throw new IllegalArgumentException("normalizePath may only be applied to an absolute path; " +
+          "argument was: " + path + "; base: " + basePath);
+    }
+
+    final String[] pathComponents = path.substring(1).split("/");
```
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: then what `if (!path.startsWith("/")) {` do?

File: src/org/exist/xslt/EXistURIResolver.java [hunk 31]
```diff
@@ -0,0 +1,201 @@
...
+
+    final int numPathComponents = Array.getLength(pathComponents);
```
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: that is question to you because this code copy of org.exist.xquery.functions.transform.EXistURIResolver

File: src/org/exist/xslt/EXistURIResolver.java [hunk 32]
```diff
@@ -0,0 +1,201 @@
...
+    final String[] simplifiedComponents = new String[numPathComponents];
+    int numSimplifiedComponents = 0;
+
+    for (final String s : pathComponents) {
```
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: I don't think that `Paths` way is right

File: src/org/exist/xslt/EXistURIResolver.java [hunk 33]
```diff
@@ -0,0 +1,201 @@
...
+      }
+      simplifiedComponents[numSimplifiedComponents++] = s;
+    }
+
+    if (numSimplifiedComponents == 0) {
+      return "/";
+    }
+
+    final StringBuilder sb = new StringBuilder(path.length());
+    for (int x = 0; x < numSimplifiedComponents; x++) {
```
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: that is question to you because this code copy of org.exist.xquery.functions.transform.EXistURIResolver

File: src/org/exist/xslt/EXistURIResolver.java [hunk 34]
```diff
@@ -0,0 +1,201 @@
...
+      sb.append("/").append(simplifiedComponents[x]);
+    }
+
+    if (path.endsWith("/")) {
+      sb.append("/");
```
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: I don't think that is right

File: src/org/exist/xslt/EXistURIResolver.java [hunk 35]
```diff
@@ -0,0 +1,201 @@
...
+    String path;
+
+    if (href.isEmpty()) {
+      path = base;
+    } else {
+      URI hrefURI = null;
+      try {
+        hrefURI = new URI(href);
+      } catch (final URISyntaxException e) {
+      }
```
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: I have no idea why it's empty, code copy from org.exist.xquery.functions.transform.EXistURIResolver

File: src/org/exist/xslt/EXistURIResolver.java [hunk 36]
```diff
@@ -0,0 +1,201 @@
...
+      return new StreamSource(url.openStream());
+    } catch (final IOException e) {
+      throw new TransformerException(e.getMessage(), e);
+    }
+  }
+
+  private Source databaseSource(final String path) throws TransformerException {
+    final XmldbURI uri = XmldbURI.create(path);
+
+    final DBBroker broker = db.getActiveBroker();
```
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: why not? No needs to allocate broker because it must be already allocated for processing.

File: src/org/exist/xslt/EXistURIResolver.java [hunk 37]
```diff
@@ -0,0 +1,201 @@
...
+    final DocumentImpl doc;
+    try {
+      doc = broker.getResource(uri, Permission.READ);
+      if (doc == null) {
+        LOG.error("Document " + path + " not found");
+        throw new TransformerException("Resource " + path + " not found in database.");
+      }
+
+      final Source source;
+      if (doc instanceof BinaryDocument) {
```
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: right, copy of org.exist.xquery.functions.transform.EXistURIResolver

File: src/org/exist/xslt/StylesheetUri.java [hunk 38]
```diff
@@ -0,0 +1,189 @@
...
+import org.exist.xmldb.XmldbURI;
+import org.exist.xquery.Constants;
+import org.xml.sax.SAXException;
+
+/**
+ * @author <a href="mailto:shabanovd@gmail.com">Dmitriy Shabanov</a>
+ */
+public class StylesheetUri implements Stylesheet {
+
+  protected final static Logger LOG = LogManager.getLogger(StylesheetUri.class);
```
Comment (shabanovd) [inline src/org/exist/xslt/StylesheetUri.java]: why not?

File: src/org/exist/xslt/StylesheetUri.java [hunk 39]
```diff
@@ -0,0 +1,189 @@
...
+
+  SAXTransformerFactory factory;
```
Comment (shabanovd) [inline src/org/exist/xslt/StylesheetUri.java]: why is it?

File: src/org/exist/xslt/StylesheetUri.java [hunk 40]
```diff
@@ -0,0 +1,189 @@
...
+import org.exist.security.PermissionDeniedException;
+import org.exist.storage.BrokerPool;
+import org.exist.storage.DBBroker;
+import org.exist.storage.lock.Lock.LockMode;
+import org.exist.storage.serializers.Serializer;
+import org.exist.xmldb.XmldbURI;
+import org.exist.xquery.Constants;
+import org.xml.sax.SAXException;
+
+/**
```
Comment (shabanovd) [inline src/org/exist/xslt/StylesheetUri.java]: done

File: src/org/exist/xslt/StylesheetUri.java [hunk 41]
```diff
@@ -0,0 +1,189 @@
...
+    } else {
+      final URL url = new URL(uri);
+      final URLConnection connection = url.openConnection();
+      long modified = connection.getLastModified();
+      if (templates == null || modified > lastModified || modified == 0) {
+        if (LOG.isDebugEnabled()) {
+          LOG.debug("compiling stylesheet " + url);
+        }
+        try (final InputStream is = connection.getInputStream()) {
+          templates = factory(broker.getBrokerPool(), errorListener).newTemplates(new StreamSource(is));
```
Comment (shabanovd) [inline src/org/exist/xslt/StylesheetUri.java]: because of `errorListener`

File: src/org/exist/xslt/StylesheetUri.java [hunk 42]
```diff
@@ -0,0 +1,189 @@
...
+    return handler;
+  }
+
+  private <E extends Exception> Templates compileTemplates(
+      DBBroker broker,
+      DocumentImpl stylesheet,
+      XSLTErrorsListener<E> errorListener)
+      throws E, TransformerConfigurationException, SAXException
+  {
+    //factory.setURIResolver(new EXistURIResolver(broker, stylesheet.getCollection().getURI().toString()));
```
Comment (shabanovd) [inline src/org/exist/xslt/StylesheetUri.java]: that is note

File: src/org/exist/xslt/TemplatesFactory.java (hunk 12 above)
Comment (shabanovd) [inline src/org/exist/xslt/TemplatesFactory.java]: nope, because `computeIfAbsent ` return `the previous value associated with the specified key`

File: src/org/exist/xslt/StylesheetUri.java (hunk 13 above)
Comment (shabanovd) [inline src/org/exist/xslt/StylesheetUri.java]: @adamretter I think that you didn't understand where concurrent issue was and how it was fixed. The problem was at `SAXTransformerFactory` use. It was shared and methods `setURIResolver` & `setErrorListener` was used. That create number of concurrent issues including `execution order bug`.

`cachedFactory` used only at places where `setErrorListener` is not required and `factory` at places where `setErrorListener` is used (templates compiling).

Comment (shabanovd) [inline src/org/exist/xslt/StylesheetUri.java]: I do not see any place where synchronization can be required. Can you point?

File: src/org/exist/xslt/TemplatesFactory.java [hunk 43]
```diff
@@ -0,0 +1,151 @@
...
+import javax.xml.transform.sax.TemplatesHandler;
+import javax.xml.transform.sax.TransformerHandler;
+import org.exist.security.PermissionDeniedException;
+import org.exist.storage.DBBroker;
+import org.exist.xquery.Constants;
+import org.exist.xquery.value.NodeValue;
+import org.w3c.dom.Document;
+import org.xml.sax.SAXException;
+
+/**
```
Comment (shabanovd) [inline src/org/exist/xslt/TemplatesFactory.java]: done

File: src/org/exist/xslt/TemplatesFactory.java (hunk 14 above)
Comment (shabanovd) [inline src/org/exist/xslt/TemplatesFactory.java]: done

File: src/org/exist/xslt/TemplatesFactory.java [hunk 44]
```diff
@@ -0,0 +1,151 @@
...
+
+  private static String uri(String stylesheet, String baseUri) {
+    String uri = stylesheet;
+    if (stylesheet.indexOf(':') == Constants.STRING_NOT_FOUND) {
+      Path f = Paths.get(stylesheet).normalize();
+      if (Files.isReadable(f)) {
+        uri = f.toUri().toASCIIString();
+      } else {
+        stylesheet = baseUri + File.separatorChar + stylesheet;
+        f = Paths.get(stylesheet).normalize();
```
Comment (shabanovd) [inline src/org/exist/xslt/TemplatesFactory.java]: done

File: src/org/exist/xslt/TemplatesFactory.java (hunk 15 above)
Comment (shabanovd) [inline src/org/exist/xslt/TemplatesFactory.java]: java support closure, why it can't be used?

File: src/org/exist/xslt/TransformerFactoryAllocator.java (hunk 16 above)
Comment (shabanovd) [inline src/org/exist/xslt/TransformerFactoryAllocator.java]: see comment above

File: src/org/exist/http/servlets/XSLTServlet.java (hunk 22 above)
Comment (shabanovd) [inline src/org/exist/http/servlets/XSLTServlet.java]: can't because of `cannot use "<>" with anonymous inner classes`

File: src/org/exist/http/servlets/XSLTServlet.java (hunk 24 above)
Comment (shabanovd) [inline src/org/exist/http/servlets/XSLTServlet.java]: Nope, because base-uri must be "" (empty string)

File: src/org/exist/xquery/functions/transform/Transform.java (hunk 26 above)
Comment (shabanovd) [inline src/org/exist/xquery/functions/transform/Transform.java]: formatting is ok here

File: src/org/exist/xquery/functions/transform/Transform.java (hunk 27 above)
Comment (shabanovd) [inline src/org/exist/xquery/functions/transform/Transform.java]: I prefer 1st version of code because it clear that default is true

File: src/org/exist/xquery/functions/transform/Transform.java (hunk 28 above)
Comment (shabanovd) [inline src/org/exist/xquery/functions/transform/Transform.java]: why not?

File: extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java (hunk 11 above)
Comment (adamretter) [inline extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java]: Okay but I think this is a bigger issue that we should all agree. We should at one of our teleconferences have a read and build a proposal for a unified URL scheme that is compatible with java.net.URI and also how we can support backwards compatibility with `xmldb:exist:/` for a period of time.

File: src/org/exist/xslt/EXistURIResolver.java (hunk 29 above)
Comment (adamretter) [inline src/org/exist/xslt/EXistURIResolver.java]: It appears that other people like @wolfgangmm have also adopted it. What do you see as the downside of using `final`?

File: src/org/exist/xslt/EXistURIResolver.java (hunk 30 above)
Comment (adamretter) [inline src/org/exist/xslt/EXistURIResolver.java]: This will cause an NPE:
```java
final String path = "/";

...

if (!path.startsWith("/")) {
  final String[] pathComponents = path.substring(1).split("/");
}
```

File: src/org/exist/xslt/EXistURIResolver.java (hunk 31 above)
Comment (adamretter) [inline src/org/exist/xslt/EXistURIResolver.java]: Okay, then it is a mistake. Can you please correct it?

File: src/org/exist/xslt/EXistURIResolver.java (hunk 32 above)
Comment (adamretter) [inline src/org/exist/xslt/EXistURIResolver.java]: Why? `Paths` is tried and tested code that we don't have to maintain, and we know that it's normalize function will likely work for all cases.

File: src/org/exist/xslt/EXistURIResolver.java (hunk 33 above)
Comment (adamretter) [inline src/org/exist/xslt/EXistURIResolver.java]: Okay, then it is a mistake. Can you please correct it?

File: src/org/exist/xslt/EXistURIResolver.java (hunk 34 above)
Comment (adamretter) [inline src/org/exist/xslt/EXistURIResolver.java]: Why don't you think that is right?

File: src/org/exist/xslt/EXistURIResolver.java (hunk 35 above)
Comment (adamretter) [inline src/org/exist/xslt/EXistURIResolver.java]: Okay, then it is a mistake. Can you please correct it?

File: src/org/exist/xslt/EXistURIResolver.java (hunk 37 above)
Comment (adamretter) [inline src/org/exist/xslt/EXistURIResolver.java]: Sure, we should think about this in the future - https://github.com/eXist-db/exist/issues/1377

File: src/org/exist/xslt/TemplatesFactory.java (hunk 15 above)
Comment (adamretter) [inline src/org/exist/xslt/TemplatesFactory.java]: It makes understanding the code harder. It is much nicer to have a clean separate subclass which has a javadoc description as to its purpose.

File: src/org/exist/xslt/TransformerFactoryAllocator.java (hunk 16 above)
Comment (adamretter) [inline src/org/exist/xslt/TransformerFactoryAllocator.java]: Sorry I don't see any comments. What/where is the comment?

File: src/org/exist/http/servlets/XSLTServlet.java (hunk 22 above)
Comment (adamretter) [inline src/org/exist/http/servlets/XSLTServlet.java]: Ok

File: src/org/exist/http/servlets/XSLTServlet.java (hunk 24 above)
Comment (adamretter) [inline src/org/exist/http/servlets/XSLTServlet.java]: Just put a check in the top of `TemplatesFactory#stylesheet` which checks if null was supplied and uses an empty string. Passing an empty string seems like it will lead to mistakes in future.

File: src/org/exist/xquery/functions/transform/Transform.java (hunk 28 above)
Comment (adamretter) [inline src/org/exist/xquery/functions/transform/Transform.java]: Because it does not show what exceptions are under consideration. Also it will catch RuntimeException's which it should not.

File: src/org/exist/xslt/EXistURIResolver.java (hunk 29 above)
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: It detracts from the understanding of the code.

File: src/org/exist/xslt/EXistURIResolver.java (hunk 30 above)
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: your code is different from code at `EXistURIResolver`

File: src/org/exist/xslt/EXistURIResolver.java (hunk 31 above)
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: Can it be at different PR?

File: src/org/exist/xslt/EXistURIResolver.java (hunk 32 above)
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: because `Paths` will not play well with urls

File: src/org/exist/xslt/EXistURIResolver.java (hunk 33 above)
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: why is that? It is ok to use any variable name, no?

File: src/org/exist/xslt/EXistURIResolver.java (hunk 34 above)
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: because `sb.append('/');` will add `/` where it was not

File: src/org/exist/xslt/EXistURIResolver.java (hunk 35 above)
Comment (shabanovd) [inline src/org/exist/xslt/EXistURIResolver.java]: that is not purpose of this PR

File: src/org/exist/xslt/TemplatesFactory.java (hunk 15 above)
Comment (shabanovd) [inline src/org/exist/xslt/TemplatesFactory.java]: not for me, this way it's much clear for me

File: src/org/exist/http/servlets/XSLTServlet.java (hunk 24 above)
Comment (shabanovd) [inline src/org/exist/http/servlets/XSLTServlet.java]: nope, that is normal practice with base-uri, similar strategy have xmlcalabash for example

File: extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java (hunk 11 above)
Comment (shabanovd) [inline extensions/modules/src/org/exist/xquery/modules/xslfo/ApacheFopProcessorAdapter.java]: I did not say that we must not support `xmldb:exist:/` but that we must start to support `xmldb:/`

File: src/org/exist/xquery/functions/transform/Transform.java (hunk 28 above)
Comment (shabanovd) [inline src/org/exist/xquery/functions/transform/Transform.java]: What is bad at catching NPE or ClassCastException and wrapped it into XPathException?

File: src/org/exist/xslt/TransformerFactoryAllocator.java (hunk 16 above)
Comment (shabanovd) [inline src/org/exist/xslt/TransformerFactoryAllocator.java]: "Show outdated" your friend. Here the copy of it:

> @adamretter I think that you didn't understand where concurrent issue was and how it was fixed. The problem was at SAXTransformerFactory use. It was shared and methods setURIResolver & setErrorListener was used. That create number of concurrent issues including execution order bug.
> 
> cachedFactory used only at places where setErrorListener is not required and factory at places where setErrorListener is used (templates compiling).

File: src/org/exist/xquery/functions/transform/Transform.java (hunk 28 above)
Comment (dizzzz) [inline src/org/exist/xquery/functions/transform/Transform.java]: Catch exception/throwable .... IMO a good enough option if you don't trust a 3rd party library.  Saxon sometimes throws unpredictable exceptions.... due to our integration.

File: src/org/exist/xslt/TemplatesFactory.java [hunk 45]
```diff
@@ -66,8 +66,7 @@ private static Stylesheet stylesheet(String stylesheet, String baseUri) {
 
     String uri = uri(stylesheet, baseUri);
 
-    cache.computeIfAbsent(uri, StylesheetResolverAndCompiler::new);
-    return cache.get(uri);
+    return cache.computeIfAbsent(uri, StylesheetResolverAndCompiler::new);
```
Comment (adamretter) [inline src/org/exist/xslt/TemplatesFactory.java]: :-)

File: src/org/exist/xslt/XSLTErrorsListener.java (hunk 9 above)
Comment (alebastrov) [inline src/org/exist/xslt/XSLTErrorsListener.java]: I would propose to use enums everywhere instead of magic numbers

File: src/org/exist/xslt/EXistURIResolver.java (hunk 29 above)
Comment (alebastrov) [inline src/org/exist/xslt/EXistURIResolver.java]: Use final only when it necessary or when there is a similar name in block of code

File: src/org/exist/xslt/EXistURIResolver.java (hunk 30 above)
Comment (alebastrov) [inline src/org/exist/xslt/EXistURIResolver.java]: I would say it;s completely wrong
~~~
if (!path.startsWith("/")) {
  final String[] pathComponents = path.substring(1).split("/");
}
~~~

Maybe you meant inverted expression like
~~~
if (path.startsWith("/")) {
  final String[] pathComponents = path.substring(1).split("/");
}
~~~

**Comment by shabanovd** [comment]
@wolfgangmm ping

**Comment by shabanovd** [comment]
@adamretter ping

**Comment by adamretter** [comment]
@shabanovd The decision for this was left with @wolfgangmm and @dizzzz from what I recall

**Comment by shabanovd** [comment]
@wolfgangmm @dizzzz should I close this PR?

**Comment by dizzzz** [comment]
@shabanovd  no, I don't think so; I remember in our Monday-telco that we agreed to have additional testcases here?

**Comment by shabanovd** [comment]
@dizzzz no, we agree to merge it next day after call ... now it's 11 days and counting

**Comment by adamretter** [comment]
@shabanovd My recollection of the call is different; I don't remember any actual agreement to merge.

I remember, that I personally didn't want to merge as the single-threaded test cases described by @rvdb https://github.com/eXist-db/exist/issues/1312#issue-211458721 are missing.

I remember @wolfgangmm saying something like "tomorrow, we will *think* about merging it".

My offer to merge once the test cases have been added, still stands; if you want it addressed more quickly than perhaps @wolfgangmm or @dizzzz can get to it.

**Comment by shabanovd** [comment]
@adamretter I think that was very clear that I don't have time to spend on it and I think that it'll be lost because nobody from "core" developers pay attention to it.

To give clear message to end-user I'll close this PR in next week if it do not get merged. I don't want to confuse anyone.

**Comment by dizzzz** [comment]
i'd need to recheck my notes but I remember there were 'threading' concerns, making us consider to atleast have some a few more tests. @shabanovd indicated not to have time for this anymore, can't recall the next step.

from my side:
- i see the added value
- this part of the code I can only perform generic code reviews - it is not my domain
- on threads/locks .... I am not not very accountable for this subject, so I cannot step in here too

so yes i'd like to see the code integrated, but  with some concerns addressed.

**Comment by wolfgangmm** [comment]
I will merge this after discussing again with @joewiz  and @ljo because it obviously indeed fixes some real issues for several users. Still tests should be added in the future. @ljo expressed interest to add some.
