### PR TITLE
Repair and improve webstart feature

### LINKED ISSUE #1146: Webstart is not working
latest development: jar files are missing in jnlp file

```xml
<?xml version="1.0" ?>
<jnlp spec="7.0" codebase="http://localhost:8080/exist/webstart/" href="exist.jnlp">
    <information>
        <title>eXist XML-DB client</title>
        <vendor>exist-db.org</vendor>
        <homepage href="http://exist-db.org"/>
        <description>Integrated command-line and gui client, entirely based on the XML:DB API and provides commands for
            most database related tasks, like creating and removing collections, user management, batch-loading XML data
            or querying.</description>
        <description kind="short">eXist XML-DB client</description>
        <description kind="tooltip">eXist XML-DB client</description>
        <icon href="jnlp_logo.jpg"/>
        <icon href="jnlp_icon_128x128.gif" width="128" height="128"/>
        <icon href="jnlp_icon_64x64.gif" width="64" height="64"/>
        <icon href="jnlp_icon_32x32.gif" width="32" height="32"/>
    </information>
    <security>
        <all-permissions/>
    </security>
    <resources>
        <property name="jnlp.packEnabled" value="true"/>
        <java version="1.8+"/>
        <jar href="exist.jar" size="4570345"/>
    </resources>
    <application-desc main-class="org.exist.client.InteractiveClient">
        <argument>-ouri=xmldb:exist://localhost:8080/exist/xmlrpc</argument>
        <argument>--no-embedded-mode</argument>
    </application-desc>
</jnlp>
```

### PR DESCRIPTION
**Pull request by dizzzz**
Fixes #1146 

- repaired unsigning / pack200'ing / normalizing 
- added missing jar files
- configure JUL to use log4j2
- add exist-db version to jnlp;

hint: pull-in PR with 'squash' option of Github webUI.

### CODE REVIEW

File: src/org/exist/webstart/JnlpJarFiles.java [hunk 1]
```diff
@@ -129,11 +144,7 @@ public JnlpJarFiles(final JnlpHelper jnlpHelper) {
      * @return list of jar files.
      */
     public List<Path> getAllWebstartJars() {
-        final List<Path> corejars = new ArrayList<>();
-
-        allFiles.values().stream().filter((file) -> (FileUtils.fileName(file).endsWith(".jar"))).forEach(corejars::add);
-
-        return corejars;
+        return allFiles.values().stream().filter((file) -> (FileUtils.fileName(file).endsWith(".jar"))).collect(Collectors.toList());
```
Comment (adamretter) [inline src/org/exist/webstart/JnlpJarFiles.java]: This will leak file handles. If you use a `Stream<Path>` then you need to close it. Consider:

```java
try(final Stream<Path> paths = allFiles.values().stream()) {
  return paths.filter((file) -> (FileUtils.fileName(file).endsWith(".jar"))).collect(Collectors.toList());
}
```

File: src/org/exist/webstart/JnlpWriter.java [hunk 2]
```diff
@@ -99,6 +100,11 @@ void writeJnlpXML(JnlpJarFiles jnlpFiles, HttpServletRequest request,
             writer.writeAttribute("codebase", codeBase);
             writer.writeAttribute("href", "exist.jnlp");
 
+            String version = SystemProperties.getInstance().getSystemProperty("product-version", null);
```
Comment (adamretter) [inline src/org/exist/webstart/JnlpWriter.java]: Consider:
```java
Optional.ofNullable(SystemProperties.getInstance().getSystemProperty("product-version", null)).ifPresent(version -> writer.writeAttribute("version", version));
```

File: src/org/exist/webstart/JnlpJarFiles.java (hunk 1 above)
Comment (shabanovd) [inline src/org/exist/webstart/JnlpJarFiles.java]: that is `stream` of `HashMap` values, not one from `Files`

File: src/org/exist/webstart/JnlpWriter.java (hunk 2 above)
Comment (shabanovd) [inline src/org/exist/webstart/JnlpWriter.java]: personally, I hate `Optional` because it make code unreadable

**Comment by dizzzz** [comment]
thank guys!
